### ISSUE TITLE
Unable to configure the plugin for Norway

### ISSUE THREAD

**Issue by lapo-gh** [bureus/MMM-Postnord#1]
I am trying to configure the plugin for Norway but somehow, it fails.
I am trying to run "node postnord-hash-generator.js new" with different values as phone number and different values as languate  -they all fail with invalid input.
The phone number has been tried in the form "+4740xxxxxx", "004740xxxxxx", "4740xxxxxx" and "40xxxxxx".
For the country, it's obvious - it should be NO.
For the language I have tried with both no and en.

As far as I can tell, there is a validation on 11 digits for the phone number (once it was changed to 10, it will work) - the validation should be based on the country code (11 for Sweden, 10 for Norway, etc.).

**Comment by bureus** [comment]
Hi @laurentiupopescu, thanks for reporting. I will look into a bug fix accordingly. So tomorrow there should be a fix if everything goes well :)

**Comment by bureus** [comment]
@laurentiupopescu : So i have fixed the issue with NO numbers, so please try again. You need to update the app, and also run 'npm install'. Best of luck, if it dont work, please reopen this ticket :)
