### ISSUE TITLE
Keeps Crashing MM2

### ISSUE THREAD

**Issue by Mrfalk** [bureus/MMM-Postnord#3]
i tryed everything with this module with no succes each time i add it to the config.js file mirror crashes and tells me to reconfigure the file

here is what im pasting in to it 

    ...
    {
            module: "MMM-Postnord",
            position: "bottom_left",
            config: {
                locale: "sv", //Optional, default is 'sv' allowed codes 'en', 'da', 'fi', 'no', 'sv'
                refreshRateMin: "60" //Optional, default is 60 min
                deliveredPackagesCooldown: "24" //Optional, hours a package should be visible until removed, default null always visible.
            }
        },
    ...

tryed without ... and in start of the file and in bottom same issue keeps crashing and telling me config file is not correct configed

**Comment by bureus** [comment]
Hi @Mrfalk, seems like I have missed some commas in the config docs. Try with this,

`{
            module: "MMM-Postnord",
            position: "bottom_left",
            config: {
                locale: "sv",
                refreshRateMin: "60",
                deliveredPackagesCooldown: "24"
            }
        },`

**Comment by bureus** [comment]
Resolved.
